require 'lita'
require 'lita/adapters/campfire'
require 'lita/adapters/campfire/callback'
require 'lita/adapters/campfire/connector'
require 'lita/adapters/campfire/room_not_available'
require 'net/http'
require 'tinder'
require 'uri'
